# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../../", "/vagrant", type: "rsync"
  config.vm.provision :shell, inline: "/vagrant/examples/vagrant/bootstrap.sh"

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network :forwarded_port, host: 8081, guest: 80
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network :forwarded_port, host: 8082, guest: 80
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/jessie64"
    debian.vm.network :forwarded_port, host: 8083, guest: 80
  end
end
