# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder "../../", "/vagrant"
  config.vm.provision :shell, inline: "/vagrant/examples/vagrant/bootstrap.sh"

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty32"
    ubuntu.vm.network :forwarded_port, host: 8081, guest: 80
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "chef/centos-6.6-i386"
    centos.vm.network :forwarded_port, host: 8082, guest: 80
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "chef/debian-7.8-i386"
    debian.vm.network :forwarded_port, host: 8083, guest: 80
  end
end
