# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.synced_folder "../../", "/vagrant"
  config.vm.provision :shell, inline: "/vagrant/examples/task-runner/bootstrap.sh"
  config.vm.network :forwarded_port, host: 6543, guest: 6543
end
